// export const initialStateLogin = false;

// export const initialList = [];

// export const initialRoom = {
//   room: {
//     tag: null,
//     title: null,
//     channel: null,
//     link: null,
//     start_date: null,
//     end_date: null,
//     question: null,
//     FCFS: null,
//     user_id: null,
//     number_of_lectures: null,
//     number_of_persons: 2,
//   },
// };
export let 로그인State = {
 user:{ 
  email:"",
  password:"",
  nickname:"",
  IsLoginBoolean:"",
  id:"",
  accessToken:"",
  id_Token:""
 }
}
export let 회원가입State = {
  signInfo:{ 
   email:"",
   password:"",
   nickname:"",
   IsLoginBoolean:"",
   id:"",
   accessToken:"",
   id_Token:""
  }
 }

export const initialState = {
  room: [
    {
      id: 1,
      tag: '과학',
      title: '공부방',
      channel: '코딩 애플',
      link: 'https://youtu.be/bv3FI_s9x0Q',
      start_date: '2021-04-01',
      end_date: '2021-04-10',
      question: 'ㅇㅇㅇ',
      FCFS: true,
      user_id: 1,
      number_of_lectures: 2,
      number_of_persons: 2,
      is_full: true,
      comment: '안녕하세요',
    },
    {
      id: 2,
      tag: '경제',
      title: '공부방',
      channel: '코딩 애플',
      link: 'https://youtu.be/bv3FI_s9x0Q',
      start_date: '2021-04-01',
      end_date: '2021-04-10',
      question: 'ㅇㅇㅇ',
      FCFS: true,
      user_id: 2,
      number_of_lectures: 2,
      number_of_persons: 2,
      is_full: true,
      comment: '안녕하세요',
    },
    {
      id: 3,
      tag: '경제',
      title: '공부방',
      channel: '코딩 애플',
      link: 'https://youtu.be/bv3FI_s9x0Q',
      start_date: '2021-04-01',
      end_date: '2021-04-10',
      question: 'ㅇㅇㅇ',
      FCFS: true,
      user_id: 3,
      number_of_lectures: 2,
      number_of_persons: 2,
      is_full: true,
      comment: '안녕하세요',
    },
    {
      id: 4,
      tag: '외국어',
      title: '공부방',
      channel: '코딩 애플',
      link: 'https://youtu.be/bv3FI_s9x0Q',
      start_date: '2021-04-01',
      end_date: '2021-04-10',
      question: 'ㅇㅇㅇ',
      FCFS: true,
      user_id: 4,
      number_of_lectures: 2,
      number_of_persons: 2,
      is_full: true,
      comment: '안녕하세요',
    },
    {
      id: 5,
      tag: '요리',
      title: '공부방',
      channel: '코딩 애플',
      link: 'https://youtu.be/bv3FI_s9x0Q',
      start_date: '2021-04-01',
      end_date: '2021-04-10',
      question: 'ㅇㅇㅇ',
      FCFS: true,
      user_id: 5,
      number_of_lectures: 2,
      number_of_persons: 2,
      is_full: true,
      comment: '안녕하세요',
    },
    {
      id: 6,
      tag: '요리',
      title: '공부방',
      channel: '코딩 애플',
      link: 'https://youtu.be/bv3FI_s9x0Q',
      start_date: '2021-04-01',
      end_date: '2021-04-10',
      question: 'ㅇㅇㅇ',
      FCFS: true,
      user_id: 6,
      number_of_lectures: 2,
      number_of_persons: 2,
      is_full: true,
      comment: '안녕하세요',
    },
    {
      id: 7,
      tag: '기타',
      title: '공부방',
      channel: '코딩 애플',
      link: 'https://youtu.be/bv3FI_s9x0Q',
      start_date: '2021-04-01',
      end_date: '2021-04-10',
      question: 'ㅇㅇㅇ',
      FCFS: true,
      user_id: 7,
      number_of_lectures: 2,
      number_of_persons: 2,
      is_full: true,
      comment: '안녕하세요',
    },
    {
      id: 8,
      tag: '운동',
      title: '공부방',
      channel: '코딩 애플',
      link: 'https://youtu.be/bv3FI_s9x0Q',
      start_date: '2021-04-01',
      end_date: '2021-04-10',
      question: 'ㅇㅇㅇ',
      FCFS: true,
      user_id: 8,
      number_of_lectures: 2,
      number_of_persons: 2,
      is_full: true,
      comment: '안녕하세요',
    },
  ],
};
